### PR TITLE
Windows statement

### PR DESCRIPTION
**Pull request by qwolphin**

### CODE REVIEW

**Comment by Zer0dot** [comment]
I think we should specify it relates only to Docker, unless there are other things that are incompatible with Windows, do you know?

**Comment by qwolphin** [comment]
The point here is Windows is not tested for now. It's tested neither with Docker nor without

 I Docker config might work from `bash on Windows` without changes

**Comment by Zer0dot** [comment]
Ok makes sense!

**Review by Zer0dot — APPROVED** [review]
LGTM. Windows for sure can work with a bit of effort, but this is a good bit of info to add.

**Pull request merged**
